FROM caisrgit/fsl:master

RUN apt update && apt upgrade -y
RUN apt install -y wget unzip python3 python-numpy python-nibabel python-setuptools cython git cmake

WORKDIR /
RUN wget "http://www.neuroimaging.at/media/qsm/TGVQSM-plus.zip"
RUN unzip /TGVQSM-plus.zip
WORKDIR /TGVQSM-master-011045626121baa8bfdd6633929974c732ae35e3
RUN python3 setup.py install

WORKDIR /
